In [43]:
import pandas as pd
import mat4py as mp
from glob import glob
from datetime import datetime

pd.set_option('io.hdf.default_format','table')

In [23]:
files = glob('data/0-raw/*.mat')

In [38]:
def date_from_filename(filename):
    parsed = filename.split('_')
    day = int(parsed[1])
    month = int(parsed[2])
    year = int(parsed[3])
    hour = int(parsed[4])
    minute = int(parsed[5][:2])
    return datetime(year, month, day, hour, minute)

In [82]:
for file in files:
    date = date_from_filename(file)
    data = pd.DataFrame(mp.loadmat(file))
    data.index = data.index.set_names('Trial')
    data['datetime'] = date
    
    eye_samples = data.explode('online_eye')
    eye_data = pd.DataFrame(eye_samples['online_eye'].tolist(), index=eye_samples.index)
    eye_data['datetime'] = date
    eye_data.set_index(['datetime', eye_data.index])
    trials = data.drop(columns=['online_eye'])
    trials = trials.set_index(['datetime',trials.index])
    eye_data.to_hdf('data/1-normalized.hdf','eye_data', append=True)
    trials.to_hdf('data/1-normalized.hdf','trials', append=True)

data/0-raw/BFnovelinac_01_02_2019_15_03.mat
data/0-raw/BFnovelinac_01_02_2019_16_08.mat
data/0-raw/BFnovelinac_03_12_2018_12_52.mat
data/0-raw/BFnovelinac_03_12_2018_13_15.mat
data/0-raw/BFnovelinac_05_12_2018_13_06.mat
data/0-raw/BFnovelinac_07_12_2018_09_21.mat
data/0-raw/BFnovelinac_07_12_2018_10_10.mat
data/0-raw/BFnovelinac_07_12_2018_11_15.mat
data/0-raw/BFnovelinac_09_11_2018_15_21.mat
data/0-raw/BFnovelinac_12_11_2018_16_19.mat
data/0-raw/BFnovelinac_12_11_2018_16_25.mat
data/0-raw/BFnovelinac_12_11_2018_16_31.mat
data/0-raw/BFnovelinac_13_11_2018_15_01.mat
data/0-raw/BFnovelinac_13_12_2018_10_54.mat
data/0-raw/BFnovelinac_13_12_2018_11_02.mat
data/0-raw/BFnovelinac_13_12_2018_11_44.mat
data/0-raw/BFnovelinac_13_12_2018_12_57.mat
data/0-raw/BFnovelinac_14_01_2019_14_44.mat
data/0-raw/BFnovelinac_14_01_2019_16_21.mat
data/0-raw/BFnovelinac_14_11_2018_15_35.mat
data/0-raw/BFnovelinac_14_11_2018_16_09.mat
data/0-raw/BFnovelinac_15_01_2019_14_28.mat
data/0-raw/BFnovelinac_15_01_2019_16_16.mat
data/0-raw/BFnovelinac_15_11_2018_15_32.mat
data/0-raw/BFnovelinac_15_11_2018_15_34.mat
data/0-raw/BFnovelinac_16_01_2019_14_29.mat
data/0-raw/BFnovelinac_16_11_2018_15_35.mat
data/0-raw/BFnovelinac_16_11_2018_16_44.mat
data/0-raw/BFnovelinac_16_11_2018_17_11.mat
data/0-raw/BFnovelinac_17_01_2019_14_54.mat
data/0-raw/BFnovelinac_17_01_2019_16_21.mat
data/0-raw/BFnovelinac_18_01_2019_14_22.mat
data/0-raw/BFnovelinac_18_01_2019_15_58.mat
data/0-raw/BFnovelinac_18_12_2018_13_36.mat
data/0-raw/BFnovelinac_19_11_2018_15_46.mat
data/0-raw/BFnovelinac_19_11_2018_16_39.mat
data/0-raw/BFnovelinac_19_11_2018_16_46.mat
data/0-raw/BFnovelinac_19_12_2018_11_02.mat
data/0-raw/BFnovelinac_19_12_2018_11_31.mat
data/0-raw/BFnovelinac_19_12_2018_15_30.mat
data/0-raw/BFnovelinac_19_12_2018_15_57.mat
data/0-raw/BFnovelinac_19_12_2018_16_27.mat
data/0-raw/BFnovelinac_19_12_2018_17_24.mat
data/0-raw/BFnovelinac_20_11_2018_15_28.mat
data/0-raw/BFnovelinac_20_11_2018_16_48.mat
data/0-raw/BFnovelinac_20_12_2018_14_56.mat
data/0-raw/BFnovelinac_20_12_2018_15_29.mat
data/0-raw/BFnovelinac_20_12_2018_15_55.mat
data/0-raw/BFnovelinac_20_12_2018_16_57.mat
data/0-raw/BFnovelinac_21_11_2018_15_32.mat
data/0-raw/BFnovelinac_21_11_2018_15_50.mat
data/0-raw/BFnovelinac_21_11_2018_16_10.mat
data/0-raw/BFnovelinac_21_11_2018_16_30.mat
data/0-raw/BFnovelinac_21_12_2018_14_56.mat
data/0-raw/BFnovelinac_21_12_2018_16_34.mat
data/0-raw/BFnovelinac_22_01_2019_14_41.mat
data/0-raw/BFnovelinac_22_01_2019_15_10.mat
data/0-raw/BFnovelinac_22_01_2019_16_01.mat
data/0-raw/BFnovelinac_22_01_2019_16_19.mat
data/0-raw/BFnovelinac_22_10_2018_15_55.mat
data/0-raw/BFnovelinac_22_10_2018_16_11.mat
data/0-raw/BFnovelinac_22_10_2018_16_39.mat
data/0-raw/BFnovelinac_23_01_2019_14_31.mat
data/0-raw/BFnovelinac_23_01_2019_15_38.mat
data/0-raw/BFnovelinac_23_01_2019_15_39.mat
data/0-raw/BFnovelinac_23_10_2018_15_14.mat
data/0-raw/BFnovelinac_23_10_2018_16_14.mat
data/0-raw/BFnovelinac_24_01_2019_15_06.mat
data/0-raw/BFnovelinac_24_10_2018_16_01.mat
data/0-raw/BFnovelinac_26_10_2018_16_48.mat
data/0-raw/BFnovelinac_29_01_2019_14_42.mat
data/0-raw/BFnovelinac_29_01_2019_16_02.mat
data/0-raw/BFnovelinac_30_01_2019_14_59.mat
data/0-raw/BFnovelinac_30_01_2019_16_38.mat
data/0-raw/BFnovelinac_31_01_2019_14_31.mat
data/0-raw/BFnovelinac_31_01_2019_16_11.mat

In [83]:
pd.read_hdf('data/1-normalized.hdf','trials')

                           fixation_required  fractals  good_trials  \
datetime            Trial
2019-02-01 15:03:00 0                      1      6212            1
                    1                      1      6202            1
                    2                      1      6302            1
                    3                      1      6212            1
                    4                      1      6202            1
...                                      ...       ...          ...
2019-01-31 16:11:00 489                    1      6202            1
                    490                    1      6101            1
                    491                    1      6212            1
                    492                    1      6312            1
                    493                    1      6302            1

                           target_amplitude  target_angle  time_fp_off  \
datetime            Trial
2019-02-01 15:03:00 0                    10             0     2.041627
                    1                    10             0     2.027416
                    2                    10             0     1.866344
                    3                    10           180     1.868525
                    4                    10           180     1.872531
...                                     ...           ...          ...
2019-01-31 16:11:00 489                  10             0     2.048566
                    490                  10           180     2.096719
                    491                  10           180     3.479869
                    492                  10             0     2.056604
                    493                  10             0     2.012973

                           time_outcome  time_target_on  trial_type
datetime            Trial
2019-02-01 15:03:00 0          4.539041        1.541559        6112
                    1          4.522012        1.519004        6102
                    2          4.361617        1.365954        6102
                    3          4.363784        1.368451        6112
                    4          4.367683        1.372509        6102
...                                 ...             ...         ...
2019-01-31 16:11:00 489        4.551228        1.548390        6102
                    490        4.584201        1.588395        6101
                    491        5.975469        2.979798        6112
                    492        4.543982        1.548147        6112
                    493        4.507564        1.504559        6102

[19181 rows x 9 columns]

In [84]:
pd.read_hdf('data/1-normalized.hdf','eye_data')

               0          1         2             3            datetime
Trial
0      39.865723  24.316406 -2.004395  7.000005e+06 2019-02-01 15:03:00
0      39.855957  24.311523 -2.005615  7.000005e+06 2019-02-01 15:03:00
0      39.848633  24.316406 -1.994934  7.000005e+06 2019-02-01 15:03:00
0      39.851074  24.296875 -1.992188  7.000005e+06 2019-02-01 15:03:00
0      39.880371  26.396484 -1.979980  7.000005e+06 2019-02-01 15:03:00
...          ...        ...       ...           ...                 ...
493    26.445312  32.478027 -1.226807  6.921394e+06 2019-01-31 16:11:00
493    26.445312  32.478027 -1.226807  6.921394e+06 2019-01-31 16:11:00
493    26.445312  32.478027 -1.226807  6.921394e+06 2019-01-31 16:11:00
493    26.445312  32.478027 -1.226807  6.921394e+06 2019-01-31 16:11:00
493    26.564941  32.604980 -1.223145  6.921394e+06 2019-01-31 16:11:00

[69818815 rows x 5 columns]